version: '3.3'

services:
  odbcbuddy:
    build:
      context: .
    container_name: odbcbuddy
    ports:
      - "54321:54321"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app  # Maps the current directory to /app in the container
      - /app/venv  # Avoids overwriting the virtual environment inside the container
    command: ["gunicorn", "-b", "0.0.0.0:54321", "app:app", "--reload"]

